default: &default
  adapter: mysql2 # 全てMySQLを使うなら、defaultもMySQLにしておくのが最もシンプル
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USERNAME'] %> # 環境変数から読み込む
  password: <%= ENV['DB_PASSWORD'] %> # 環境変数から読み込む
  host: <%= ENV['DB_HOST'] %>         # 環境変数から読み込む
  port: <%= ENV['DB_PORT'] %>

development:
  <<: *default
  database: portfolio_development # 環境に応じて変更

test:
  <<: *default
  database: portfolio_test # 環境に応じて変更

production:
  <<: *default
  database: <%= ENV['DB_DATABASE'] %> # 環境変数から読み込む